### ISSUE TITLE
膜拜 原来已经有大佬做过了，我又重新造了遍轮子

### ISSUE THREAD

**Issue by kala51773** [jiongjiongJOJO/AHSTU_SPCP_2#2]

**Comment by jiongjiongJOJO** [comment]
最近更新了一个返校时间，我一直没改，这个也可以正常使用。没有时间更新，如果有能力可以给个pr更新一下~ε(*･ω･)_/ﾟ:･☆

**Comment by jiongjiongJOJO** [comment]
> 最近更新了一个返校时间，我一直没改，这个也可以正常使用。没有时间更新，如果有能力可以给个pr更新一下~ε(*･ω･)_/ﾟ:･☆

已更新🥳🥳🥳
